Repository knative/networking, pull requests merged in 2020-07, with the labels that each got.

#30 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#31 Fix invalid links
  pkg/apis/networking/v1alpha1/domain_types.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/realm_types.go
  pkg/apis/networking/v1alpha1/serverlessservice_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#22 Removes unwanted timeout setting
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
Labels: approved, cla: yes, lgtm, size/S

#34 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1_tests.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#36 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#37 Minor test flow nits
  pkg/apis/config/defaults_test.go
Labels: approved, cla: yes, lgtm, size/S

#38 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#40 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.mod
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/test/logging/logger_writer.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#39 Revert "Removes unwanted timeout setting"
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
Labels: approved, cla: yes, lgtm, size/S

#42 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/test/logging/logger_writer.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#41 Make use of the class-based genreconciler.
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/stub/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#43 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/state.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#44 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm64.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#45 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#46 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#47 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/proxy.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/controller/helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#49 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#51 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/state.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#52 Move knative.dev/serving/pkg/network to knative.dev/networking/pkg
  go.mod
  go.sum
  pkg/bufferpool.go
  pkg/bufferpool_test.go
  pkg/doc.go
  pkg/ingress/doc.go
  pkg/ingress/ingress.go
  pkg/ingress/ingress_test.go
  pkg/network.go
  pkg/network_test.go
  pkg/probe_handler.go
  pkg/probe_handler_test.go
  pkg/stats.go
  pkg/stats_test.go
  pkg/status/status.go
  pkg/status/status_test.go
  pkg/testdata/config-network.yaml
  pkg/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#53 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#54 Correct package name and properly running deepcopy-gen
  hack/update-codegen.sh
  pkg/bufferpool.go
  pkg/bufferpool_test.go
  pkg/doc.go
  pkg/network.go
  pkg/network_test.go
  pkg/probe_handler.go
  pkg/probe_handler_test.go
  pkg/stats.go
  pkg/stats_test.go
  pkg/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S
