Repository knative/networking, pull requests merged in 2020-12, with the labels that each got.

#286 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#287 Integrate the gopath hacks to allow for codegen anywhere.
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/S

#288 Fix the probe package with prober constants and a free func
  pkg/probe/doc.go
  pkg/probe/handler.go
  pkg/probe/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#289 Move the drainer helper from pkg to the networking.
  pkg/handlers/drain.go
  pkg/handlers/drain_test.go
  pkg/probe/doc.go
  pkg/probe/handler.go
  pkg/probe/handler_test.go
Labels: approved, cla: yes, lgtm, size/XL

#290 Move the prober library to the networking
  pkg/prober/doc.go
  pkg/prober/prober.go
  pkg/prober/prober_test.go
Labels: approved, cla: yes, lgtm, size/XL

#291 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#292 Remove the pkg references for prober
  go.mod
  go.sum
  pkg/probe_handler_test.go
  pkg/status/status.go
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/prober/doc.go
  vendor/knative.dev/pkg/network/prober/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#293 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#294 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#295 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#296 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#300 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#305 Remove CreateFlakyService util function and flaky test image
  test/conformance/ingress/util.go
  test/test_images/flaky/main.go
  test/test_images/flaky/service.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/L

#307 Add the config map setting for the gradual rollout
  config/config-network.yaml
Labels: approved, cla: yes, lgtm, size/XS

#308 Parse and set the rollout duration setting
  pkg/network.go
  pkg/network_test.go
Labels: approved, cla: yes, lgtm, size/M

#310 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/testing/conditions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#311 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#306 Add httpOption to KIngress spec
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/ingress_validation.go
  pkg/apis/networking/v1alpha1/ingress_validation_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#312 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#313 Avoid recreating the logger in the ingress prober
  pkg/status/status.go
  pkg/status/status_test.go
Labels: approved, cla: yes, lgtm, size/S

#314 Revert "add httpoption to kingress spec (#306)"
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/ingress_validation.go
  pkg/apis/networking/v1alpha1/ingress_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#315 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#316 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#318 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#317 Add httpoption to ingress spec
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/ingress_validation.go
  pkg/apis/networking/v1alpha1/ingress_validation_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#319 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#320 Use `ko` 0.6.0
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#322 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#323 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#325 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
