Repository knative/networking, pull requests merged in 2020-06, with the labels that each got.

#5 Update OWNERS.
  OWNERS
Labels: approved, cla: yes, lgtm, size/S

#7 Add reviewers to OWNERS.
  OWNERS
Labels: approved, cla: yes, lgtm, size/S

#8 Add a barebone e2e-tests.sh
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#9 Update deps to pick up latest pkg.
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#10 Cherry pick latest API changes from Serving
  pkg/apis/networking/v1alpha1/certificate_lifecycle_test.go
  pkg/apis/networking/v1alpha1/certificate_types.go
  pkg/apis/networking/v1alpha1/certificate_types_test.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/ingress_types_test.go
  pkg/apis/networking/v1alpha1/ingress_validation.go
  pkg/apis/networking/v1alpha1/ingress_validation_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_lifecycle_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_types.go
  pkg/apis/networking/v1alpha1/serverlessservice_types_test.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
Labels: approved, cla: yes, lgtm, size/L

#11 Cherry-pick "Always consider ObservedGeneration for scaling & network types IsReady (#8187)"
  pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  pkg/apis/networking/v1alpha1/certificate_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_lifecycle.go
  pkg/apis/networking/v1alpha1/serverlessservice_lifecycle_test.go
  test/conformance/certificate/utils.go
  test/ingress.go
Labels: approved, cla: yes, lgtm, size/M

#13 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
Labels: approved, cla: yes, lgtm, size/XXL

#14 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#15 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#16 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/testing.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#17 Regen deps
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/go.opencensus.io/Makefile
  vendor/go.opencensus.io/plugin/ocgrpc/client.go
  vendor/go.opencensus.io/plugin/ocgrpc/server.go
  vendor/go.opencensus.io/plugin/ocgrpc/trace_common.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/b3/b3.go
  vendor/go.opencensus.io/stats/record.go
  vendor/go.opencensus.io/stats/view/export.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/go.opencensus.io/trace/lrumap.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#19 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/stub/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/stub/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/stub/reconciler.go
  vendor/k8s.io/api/admission/v1/doc.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1/generated.proto
  vendor/k8s.io/api/admission/v1/register.go
  vendor/k8s.io/api/admission/v1/types.go
  vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#20 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#21 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/tracing/propagation/http_format_sequence.go
  vendor/knative.dev/pkg/tracing/propagation/tracecontextb3/http_format.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#23 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#24 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/leaderelection/ordinal.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#25 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/.travis.yml
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
  vendor/github.com/kelseyhightower/envconfig/README.md
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/go.mod
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/leaderelection/ordinal.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#28 Update {pkg,test-infra,caching} to release-0.16
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS
