Repository knative/networking, pull requests merged in 2020-11, with the labels that each got.

#258 Move the constant to the networking package where it belongs
  pkg/apis/networking/register.go
Labels: approved, cla: yes, lgtm, size/XS

#259 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#260 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#261 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#263 Enable tparallel linter and make sure all subtests are parallel
  .golangci.yaml
  test/conformance/ingress/class.go
  test/conformance/ingress/headers.go
  test/conformance/ingress/path.go
  test/conformance/ingress/timeout.go
  test/conformance/ingress/tls.go
  test/conformance/ingress/visibility.go
Labels: approved, cla: yes, lgtm, size/S

#262 Enable errorlint and fix existing issues
  .golangci.yaml
  test/conformance/ingress/util.go
  test/test_images/grpc-ping/main.go
  test/test_images/runtime/handlers/proc.go
Labels: approved, cla: yes, lgtm, size/S

#264 Instrument the Retry logic, so it is clearer when we are retrying failures
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/S

#265 Use a different hostname per variant.
  test/conformance/ingress/visibility.go
Labels: approved, cla: yes, lgtm, size/S

#266 Fix iterator capture bug.
  test/conformance/ingress/visibility.go
Labels: approved, cla: yes, lgtm, size/XS

#267 This drops the somewhat gratuitous use of t.Parallel in TLS tests.
  test/conformance/ingress/tls.go
Labels: approved, cla: yes, lgtm, size/S

#268 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#270 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#269 Fix a few more occurrences of divisive language
  config/placeholder.go
  pkg/bufferpool_test.go
  pkg/status/status_test.go
Labels: approved, cla: yes, lgtm, size/S

#271 Remove cmd directory
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/LICENSE
  cmd/controller/kodata/VENDOR-LICENSE
  cmd/controller/kodata/refs
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/refs
Labels: approved, cla: yes, lgtm, size/XS

#272 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#273 drop require statements, bump go to 1.15 and k8s.io to v0.18.12
  .github/workflows/knative-downstream.yaml
  go.mod
  go.sum
  hack/update-k8s-deps.sh
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#274 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#275 Surface the CreateIngress test helper
  test/conformance/ingress/class.go
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/XS

#276 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#278 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#277 Add a conformance test to make sure multiple rules work
  test/conformance/ingress/rule.go
  test/conformance/ingress/run.go
Labels: approved, cla: yes, lgtm, size/M

#279 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#280 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#281 Switch map key to NamespacedName and more safely generate accessor
  pkg/status/status.go
  pkg/testing/status/fake.go
Labels: approved, cla: yes, lgtm, size/M

#282 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#283 Drop unused test images, constants and helpers
  test/conformance.go
  test/crd.go
  test/e2e_constants.go
  test/test_images/failing/failing.go
  test/test_images/failing/service.yaml
  test/test_images/helloworld/helloworld.go
  test/test_images/helloworld/helloworld.yaml
  test/test_images/helloworld/service.yaml
  test/util.go
Labels: approved, cla: yes, lgtm, size/L

#284 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#285 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
