Repository knative/networking, pull requests merged in 2020-08, with the labels that each got.

#56 Update realm and domain CRD for Kubernetes 1.6
  config/300-domain.yaml
  config/300-realm.yaml
Labels: approved, cla: yes, lgtm, size/M

#58 Add json tags to RealmSpec
  pkg/apis/networking/v1alpha1/realm_types.go
  pkg/apis/networking/v1alpha1/realm_validation.go
  pkg/apis/networking/v1alpha1/realm_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#59 Move prober utility from knative.dev/serving to be used by network conformance tests
  go.mod
  test/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#60 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/klog/v2/LICENSE
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/any_str.go
  vendor/github.com/json-iterator/go/config.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_optional.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/reflect_struct_encoder.go
  vendor/github.com/json-iterator/go/stream.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/config.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/increase_level.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/utils/trace/README.md
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#61 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#63 Centralize logstream initialization.
  test/conformance.go
  test/conformance/ingress/basic.go
  test/conformance/ingress/grpc.go
  test/conformance/ingress/headers.go
  test/conformance/ingress/hosts.go
  test/conformance/ingress/path.go
  test/conformance/ingress/percentage.go
  test/conformance/ingress/retry.go
  test/conformance/ingress/timeout.go
  test/conformance/ingress/tls.go
  test/conformance/ingress/update.go
  test/conformance/ingress/visibility.go
  test/conformance/ingress/websocket.go
  test/defaultsystem/system.go
Labels: approved, cla: yes, lgtm, size/M

#62 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#64 Revert "Revert "Removes unwanted timeout setting (#22)" (#39)"
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
Labels: approved, cla: yes, lgtm, size/S

#65 Adds README.md to conformance tests after serving->networking move
  test/conformance/ingress/README.md
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/L

#69 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informed_watcher.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#68 [master] Format markdown
  test/conformance/ingress/README.md
Labels: approved, cla: yes, lgtm, size/XS

#71 Remove sample configs from sample-controller
  config/100-namespace.yaml
  config/200-clusterrole.yaml
  config/200-serviceaccount.yaml
  config/201-clusterrolebinding.yaml
  config/300-addressableservice.yaml
  config/400-webhook-service.yaml
  config/500-webhook-configuration.yaml
  config/config-logging.yaml
  config/config-observability.yaml
  config/controller.yaml
  config/webhook.yaml
  example.yaml
Labels: approved, cla: yes, lgtm, size/XL

#72 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#73 [RELEASE] Pin test-infra, caching and pkg to release-0.17 branch
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#70 Fix README.md to contain summary of the API and where to find code.
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: approved, cla: yes, lgtm, size/L

#76 Randomize the hostnames in TestMultipleHosts.
  test/conformance/ingress/hosts.go
Labels: approved, cla: yes, lgtm, size/XS

#78 [release-0.17] Randomize the hostnames in TestMultipleHosts. (#76)
  test/conformance/ingress/hosts.go
Labels: approved, cla: yes, lgtm, size/XS

#79 Retry Creates on resourcequota conflicts.
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/M

#75 Warm the reverse proxy's DNS cache before serving requests.
  pkg/probe_handler.go
  test/test_images/httpproxy/httpproxy.go
Labels: approved, cla: yes, lgtm, size/M

#80 Delete the stale comment
  pkg/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS

#77 Introduce new network.knative.dev/visibility for VisibilityLabelKey
  pkg/network.go
Labels: approved, cla: yes, lgtm, size/XS

#81 Another instance of #76
  test/conformance/ingress/visibility.go
Labels: approved, cla: yes, lgtm, size/XS

#82 Include Get in the UpdateRetry.
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/S

#86 [release 0.17] Cherrypick #79 and #82
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/M

#84 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#83 [master] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#85 [release 0.17] Another instance of #76 (#81)
  test/conformance/ingress/visibility.go
Labels: approved, cla: yes, lgtm, size/XS

#88 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#89 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#90 Avoid more host collisions
  test/conformance/ingress/rewrite.go
Labels: approved, cla: yes, lgtm, size/S

#93 Add ingress conformance test for cluster local service domain short names
  test/conformance/ingress/visibility.go
Labels: approved, cla: yes, lgtm, size/S

#94 Adjust the timeout test values a bit.
  test/conformance/ingress/timeout.go
Labels: approved, cla: yes, lgtm, size/XS

#96 Add scheme
  test/conformance/ingress/rewrite.go
Labels: approved, cla: yes, lgtm, size/XS

#95 Prefer t.Cleanup over test.CleanupOnInterrupt and defer cancel.
  test/conformance/ingress/basic.go
  test/conformance/ingress/grpc.go
  test/conformance/ingress/headers.go
  test/conformance/ingress/hosts.go
  test/conformance/ingress/path.go
  test/conformance/ingress/percentage.go
  test/conformance/ingress/retry.go
  test/conformance/ingress/rewrite.go
  test/conformance/ingress/timeout.go
  test/conformance/ingress/tls.go
  test/conformance/ingress/util.go
  test/conformance/ingress/visibility.go
  test/conformance/ingress/websocket.go
Labels: approved, cla: yes, lgtm, size/L

#97 [release 0.17] cherrypick #90 and #96
  test/conformance/ingress/rewrite.go
Labels: approved, cla: yes, lgtm, size/S

#99 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#101 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/kmp/diff.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#104 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#102 Enable kingress composition.
  pkg/ingress/ingress.go
  pkg/ingress/ingress_test.go
  pkg/network.go
  pkg/status/status.go
  pkg/status/status_test.go
Labels: approved, cla: yes, lgtm, size/L

#105 Remove Istio specific constants (to be moved to net-istio).
  pkg/apis/networking/register.go
Labels: approved, cla: yes, lgtm, size/XS

#108 Clean up obsolete includeOutboundIPRanges in config-network
  pkg/network.go
  pkg/testdata/config-network.yaml
Labels: approved, cla: yes, lgtm, size/S

#114 Avoid fixed-name collisions
  test/conformance/ingress/visibility.go
Labels: approved, cla: yes, lgtm, size/XS

#115 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#116 [master] Format markdown
  docs/conformance.md
Labels: approved, cla: yes, lgtm, size/M

#118 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#119 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#120 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#122 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#125 Change visibility label to networking.knative.dev from network.knative.dev
  pkg/network.go
Labels: approved, cla: yes, lgtm, size/XS

#124 Add constant for label to disable AutoTLS
  pkg/apis/networking/register.go
Labels: approved, cla: yes, lgtm, size/XS

#127 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/system/testing/names.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#126 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#128 Change DisableAutoTLSLabelKey to DisableAutoTLSAnnotationKey
  pkg/apis/networking/register.go
Labels: approved, cla: yes, lgtm, size/XS

#130 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
