Repository knative/networking, pull requests merged in 2020-09, with the labels that each got.

#131 [master] Update GitHub Actions
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#132 Deprecate Retry field in KIngress and remove conformance test
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/ingress_validation.go
  pkg/apis/networking/v1alpha1/ingress_validation_test.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  test/conformance/ingress/retry.go
  test/conformance/ingress/run.go
Labels: approved, cla: yes, lgtm, size/L

#133 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#129 Make ingress.spec.visibility deprecated
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_types.go
Labels: approved, cla: yes, lgtm, size/M

#134 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#135 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#137 Deprecate ingress.status.LoadBalancer status field
  pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S

#139 Make kingress conformance amenable to KinD
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/M

#140 Fix typo
  pkg/apis/networking/v1alpha1/ingress_lifecycle.go
Labels: approved, cla: yes, lgtm, size/XS

#138 Add KIngress conformance test for probe request
  test/conformance/ingress/headers.go
  test/conformance/ingress/run.go
Labels: approved, cla: yes, lgtm, size/M

#143 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#57 Move config-network.yaml from knative.dev/serving to knative.dev/networking
  config/config-network.yaml
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/L

#145 Use RetryTestErrors
  go.mod
  go.sum
  test/conformance/ingress/util.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#146 Fix an issue with the new test.
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/XS

#148 Retry Gets
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/S

#149 Remove outdated Gopkg related files.
  Gopkg.lock
  Gopkg.toml
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/XXL

#150 Add linting config and fix issues.
  .golangci.yaml
  pkg/apis/config/defaults.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
Labels: approved, cla: yes, lgtm, size/M

#151 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#153 Add a dummy file so we can import configs
  config/dummy.go
Labels: approved, cla: yes, lgtm, size/S

#154 Move Kcert and KIngress CRDs from serving to networking repo
  config/certificate.yaml
  config/domain.yaml
  config/ingress.yaml
  config/realm.yaml
Labels: approved, cla: yes, lgtm, size/L

#156 Remove tagHeaderBasedRouting example from config-network.yaml
  config/config-network.yaml
  hack/update-checksums.sh
Labels: approved, cla: yes, lgtm, size/XS

#158 Add a negative test for ingress.class handling
  test/conformance/ingress/class.go
  test/conformance/ingress/run.go
  test/conformance/ingress/util.go
Labels: approved, cla: yes, lgtm, size/L

#157 Add conformance test for omitted timeout
  test/conformance/ingress/timeout.go
Labels: approved, cla: yes, lgtm, size/S

#159 Update serverlessservice_validation.go
  pkg/apis/networking/v1alpha1/serverlessservice_validation.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#160 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#161 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#164 Remove short-names for gateways with all-numeric Top Level Domains
  pkg/ingress/ingress.go
  pkg/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/S

#163 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#167 Some followup to the #164
  pkg/ingress/ingress.go
  pkg/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/M

#162 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#168 Give the pools an explicit capacity to not block unnecessarily.
  test/conformance/ingress/path.go
  test/conformance/ingress/percentage.go
  test/conformance/ingress/visibility.go
Labels: approved, cla: yes, lgtm, size/XS

#170 Update README.md
  test/conformance/ingress/README.md
Labels: approved, cla: yes, lgtm, size/S

#171 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#173 Minor README.md updates
  test/conformance/ingress/README.md
Labels: approved, cla: yes, lgtm, size/XS

#174 Fix nits from deepsource
  pkg/apis/networking/v1alpha1/certificate_validation.go
  test/conformance/ingress/class.go
Labels: approved, cla: yes, lgtm, size/M

#175 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#177 Add code coverage for networking package as well
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/S

#178 Various fixes around the networking repo
  test/conformance/ingress/class.go
  test/conformance/ingress/grpc.go
  test/conformance/ingress/util.go
  test/conformance/ingress/websocket.go
  test/test_images/httpproxy/httpproxy.go
Labels: approved, cla: yes, lgtm, size/M

#180 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#179 [master] Format markdown
  test/conformance/ingress/README.md
Labels: approved, cla: yes, lgtm, size/XS

#181 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#182 [Release-0.18] Pin deps to release-0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#185 Move FakeStatusManager for testing StatusManager calls
  pkg/status/status.go
  pkg/testing/status/fake.go
  pkg/testing/status/fake_test.go
Labels: approved, cla: yes, lgtm, size/L

#186 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#188 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#184 Support skip-tests option to skip some specific tests in alpha or beta features
  test/conformance/ingress/run.go
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/L

#189 Fix the t.Formatter calls to match style checker
  pkg/apis/config/store_test.go
  pkg/apis/networking/v1alpha1/certificate_lifecycle_test.go
  pkg/apis/networking/v1alpha1/certificate_validation_test.go
  pkg/apis/networking/v1alpha1/domain_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_defaults_test.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_validation_test.go
  pkg/apis/networking/v1alpha1/realm_lifecycle_test.go
  pkg/apis/networking/v1alpha1/register_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_lifecycle_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_validation_test.go
  pkg/ingress/ingress_test.go
  pkg/network_test.go
  pkg/status/status_test.go
  test/conformance/certificate/nonhttp01/certificate.go
  test/conformance/certificate/utils.go
  test/conformance/ingress/grpc.go
  test/conformance/ingress/headers.go
  test/conformance/ingress/path.go
  test/conformance/ingress/percentage.go
  test/conformance/ingress/util.go
  test/conformance/ingress/visibility.go
  test/conformance/ingress/websocket.go
Labels: approved, cla: yes, lgtm, size/M

#190 This fixes logger and fmt strings
  test/conformance/ingress/grpc.go
  test/conformance/ingress/websocket.go
  test/test_images/flaky/main.go
Labels: approved, cla: yes, lgtm, size/S

#191 Enable extended linting and fix the respective issues
  .golangci.yaml
  pkg/apis/networking/v1alpha1/certificate_types.go
  pkg/apis/networking/v1alpha1/domain_defaults.go
  pkg/apis/networking/v1alpha1/domain_validation.go
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/ingress_validation.go
  pkg/apis/networking/v1alpha1/realm_defaults.go
  pkg/apis/networking/v1alpha1/realm_lifecycle.go
  pkg/apis/networking/v1alpha1/realm_types.go
  pkg/apis/networking/v1alpha1/realm_validation.go
  pkg/apis/networking/v1alpha1/serverlessservice_defaults.go
  pkg/apis/networking/v1alpha1/serverlessservice_types.go
  pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  pkg/status/status.go
  test/clients.go
  test/conformance/ingress/util.go
  test/e2e_flags.go
  test/test_images/runtime/handlers/request.go
  test/types/runtime.go
Labels: approved, cla: yes, lgtm, size/L

#192 Migrate constants that are only used in Serving
  pkg/apis/networking/ports.go
  pkg/apis/networking/register.go
Labels: approved, cla: yes, lgtm, size/M
