Repository knative/networking, pull requests merged in 2021-12, with the labels that each got.

#585 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, approved, size/XS

#584 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#586 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#588 Simplify the HTTP Proxy test image a bit
  go.mod
  go.sum
  test/test_images/httpproxy/httpproxy.go
  third_party/VENDOR-LICENSE/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/XL

#589 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#590 Bump dependencies to latest
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#591 Reintroduce DNS caching into the proxy image
  go.mod
  go.sum
  test/test_images/httpproxy/httpproxy.go
  third_party/VENDOR-LICENSE/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#593 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#594 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#596 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#595 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#597 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/XS
