Repository knative/networking, pull requests merged in 2021-01, with the labels that each got.

#326 Add Namespace field to ClusterDomainClaim
  pkg/apis/networking/v1alpha1/domainclaim_types.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/S

#327 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#328 Use symlink for testdata version of config-network.yaml
  pkg/testdata/config-network.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/L

#329 As per discussion with @mattmoor keep drainer in pkg
  pkg/handlers/drain.go
  pkg/handlers/drain_test.go
Labels: approved, cla: yes, lgtm, size/L

#330 Add config to disable auto-creation of domain claims
  config/config-network.yaml
  pkg/network.go
  pkg/network_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#331 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#332 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#333 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#334 Move RewriteHost conformance tests to Beta
  test/conformance/ingress/run.go
Labels: approved, cla: yes, lgtm, size/XS

#336 Remove out-of-date comment
  pkg/apis/networking/v1alpha1/ingress_types.go
Labels: approved, cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#337 [] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/networking/v1alpha1/certificate/filtered/certificate.go
  pkg/client/injection/informers/networking/v1alpha1/certificate/filtered/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/clusterdomainclaim/filtered/clusterdomainclaim.go
  pkg/client/injection/informers/networking/v1alpha1/clusterdomainclaim/filtered/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/domain/filtered/domain.go
  pkg/client/injection/informers/networking/v1alpha1/domain/filtered/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/ingress/filtered/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/ingress/filtered/ingress.go
  pkg/client/injection/informers/networking/v1alpha1/realm/filtered/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/realm/filtered/realm.go
  pkg/client/injection/informers/networking/v1alpha1/serverlessservice/filtered/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/serverlessservice/filtered/serverlessservice.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#338 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#339 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#340 Move TestProbeHeaders tests to stable, TestTagHeaders tests to beta
  test/conformance/ingress/run.go
Labels: approved, cla: yes, lgtm, size/XS
