Repository knative/networking, pull requests merged in 2021-08, with the labels that each got.

#473 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#477 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#478 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#475 Bump Golang version to 1.16
  go.mod
Labels: cla: yes, lgtm, approved, size/XS

#468 Add a new test case to request unexpected hash
  test/conformance/ingress/headers.go
Labels: cla: yes, lgtm, approved, size/S

#476 Use actual cluster domain for TestRewriteHost
  test/conformance/ingress/rewrite.go
Labels: cla: yes, lgtm, approved, size/XS

#480 [main] Format Go code
  hack/tools.go
  test/conformance/certificate/http01/run_test.go
  test/conformance/certificate/nonhttp01/run_test.go
  test/conformance/ingress/run_test.go
Labels: cla: yes, lgtm, approved, size/XS

#481 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/networking/v1alpha1/certificate/certificate.go
  pkg/client/injection/informers/networking/v1alpha1/certificate/filtered/certificate.go
  pkg/client/injection/informers/networking/v1alpha1/clusterdomainclaim/clusterdomainclaim.go
  pkg/client/injection/informers/networking/v1alpha1/clusterdomainclaim/filtered/clusterdomainclaim.go
  pkg/client/injection/informers/networking/v1alpha1/domain/domain.go
  pkg/client/injection/informers/networking/v1alpha1/domain/filtered/domain.go
  pkg/client/injection/informers/networking/v1alpha1/ingress/filtered/ingress.go
  pkg/client/injection/informers/networking/v1alpha1/ingress/ingress.go
  pkg/client/injection/informers/networking/v1alpha1/realm/filtered/realm.go
  pkg/client/injection/informers/networking/v1alpha1/realm/realm.go
  pkg/client/injection/informers/networking/v1alpha1/serverlessservice/filtered/serverlessservice.go
  pkg/client/injection/informers/networking/v1alpha1/serverlessservice/serverlessservice.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/dynamicclient/dynamicclient.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved

#482 Revert "Add a new test case to request unexpected hash (#468)"
  test/conformance/ingress/headers.go
Labels: cla: yes, lgtm, approved, size/S

#483 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#484 Clean up deprecated fields
  pkg/apis/networking/v1alpha1/ingress_defaults.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
Labels: cla: yes, lgtm, approved, size/M

#485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#487 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#493 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S
