Repository knative/networking, pull requests merged in 2021-03, with the labels that each got.

#358 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#360 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#361 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#362 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#363 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/XS

#365 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#366 Drop unnecessary occurrences of master
  pkg/apis/networking/generic_types.go
  test/conformance/ingress/README.md
Labels: approved, cla: yes, lgtm, size/XS

#364 Update KIngress rule path to be a literal string
  pkg/apis/networking/v1alpha1/ingress_types.go
Labels: approved, cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#368 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#367 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#370 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#369 Add arturenault as networking reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#371 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#373 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#372 [Automated] Update actions
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#374 rename downstream-test-go to actions-downstream-test
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/XS

#375 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#376 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#377 Add pod-addressability config to config-network
  config/config-network.yaml
  pkg/network.go
  pkg/network_test.go
Labels: approved, cla: yes, lgtm, size/M

#380 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#381 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#382 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
