Repository knative/networking, pull requests merged in 2021-11, with the labels that each got.

#549 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#550 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/XS

#551 [release-1.0] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#554 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#543 asLabelSelector - don't mutate the target if the property is not set
  pkg/network.go
Labels: cla: yes, lgtm, approved, size/XS

#556 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#555 Adds k8s recommended labels
  config/certificate.yaml
  config/config-network.yaml
  config/domain-claim.yaml
  config/domain.yaml
  config/ingress.yaml
  config/realm.yaml
  config/serverlessservice.yaml
Labels: cla: yes, lgtm, approved, size/S, kind/enhancement

#557 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#558 Replaces part-of with name k8s label
  config/certificate.yaml
  config/config-network.yaml
  config/domain-claim.yaml
  config/domain.yaml
  config/ingress.yaml
  config/realm.yaml
  config/serverlessservice.yaml
Labels: cla: yes, lgtm, approved, size/S

#559 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, approved, size/M

#560 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#561 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#563 bump downstream workflow to use go1.17
  .github/workflows/knative-downstream.yaml
Labels: cla: yes, lgtm, approved, size/XS

#564 drop used stubs
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/stub/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/stub/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/stub/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/stub/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/stub/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/stub/reconciler.go
Labels: cla: yes, lgtm, approved, size/XS

#565 remove networking.DisableWildcardCertLabelKey
  pkg/apis/networking/register.go
Labels: cla: yes, lgtm, approved, size/XS

#566 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#568 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#569 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#567 include helpers to lookup annotations
  pkg/apis/networking/register.go
Labels: cla: yes, lgtm, approved, size/S

#570 Use Protocol instead of Option
  pkg/apis/networking/register.go
Labels: cla: yes, lgtm, approved, size/XS

#571 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#562 Introduce kebab-case annotation variants
  pkg/apis/networking/metadata_validation.go
  pkg/apis/networking/metadata_validation_test.go
  pkg/apis/networking/register.go
Labels: cla: yes, lgtm, approved, size/L

#572 revert the case change for the wildcard cert domain label
  pkg/apis/networking/register.go
Labels: cla: yes, lgtm, approved, size/XS

#573 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#574 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#577 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#576 refactor some annotation constants using the kmap utility
  pkg/apis/networking/register.go
Labels: cla: yes, lgtm, approved, size/M

#579 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#580 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#581 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#582 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#583 Drop implicit dependencies from go.mod
  go.mod
  go.sum
  vendor/github.com/go-openapi/jsonpointer/.travis.yml
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/jsonreference/.golangci.yml
  vendor/github.com/go-openapi/jsonreference/.travis.yml
  vendor/github.com/go-openapi/jsonreference/README.md
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/.travis.yml
  vendor/github.com/go-openapi/swag/README.md
  vendor/github.com/go-openapi/swag/convert.go
  vendor/github.com/go-openapi/swag/convert_types.go
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/loading.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/josharian/intern/README.md
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/josharian/intern/intern.go
  vendor/github.com/josharian/intern/license.md
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved
