Repository knative/networking, pull requests merged in 2022-12, with the labels that each got.

#739 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#743 [release-1.7] Cherry picks
  .github/workflows/knative-downstream.yaml
  pkg/apis/networking/v1alpha1/certificate_lifecycle_test.go
  pkg/apis/networking/v1alpha1/certificate_types_test.go
  pkg/apis/networking/v1alpha1/domain_lifecycle_test.go
  pkg/apis/networking/v1alpha1/domain_types_test.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_types_test.go
  pkg/apis/networking/v1alpha1/realm_lifecycle_test.go
  pkg/apis/networking/v1alpha1/realm_types_test.go
  pkg/apis/networking/v1alpha1/register_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_lifecycle_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_types_test.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/config/config.go
  pkg/ingress/ingress.go
  pkg/prober/prober.go
  test/conformance/certificate/http01/certificate.go
  test/conformance/ingress/util.go
  test/test_images/runtime/handlers/cgroup.go
  test/test_images/runtime/handlers/file_access_attempt.go
  test/test_images/wsserver/echo.go
  test/util.go
Labels: lgtm, approved, size/L

#744 [release-1.6] Cherry picks
  .github/workflows/knative-downstream.yaml
  pkg/apis/networking/v1alpha1/certificate_lifecycle_test.go
  pkg/apis/networking/v1alpha1/certificate_types_test.go
  pkg/apis/networking/v1alpha1/domain_lifecycle_test.go
  pkg/apis/networking/v1alpha1/domain_types_test.go
  pkg/apis/networking/v1alpha1/ingress_lifecycle_test.go
  pkg/apis/networking/v1alpha1/ingress_types_test.go
  pkg/apis/networking/v1alpha1/realm_lifecycle_test.go
  pkg/apis/networking/v1alpha1/realm_types_test.go
  pkg/apis/networking/v1alpha1/register_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_lifecycle_test.go
  pkg/apis/networking/v1alpha1/serverlessservice_types_test.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/config/config.go
  pkg/ingress/ingress.go
  pkg/prober/prober.go
  test/conformance/certificate/http01/certificate.go
  test/conformance/ingress/util.go
  test/test_images/runtime/handlers/cgroup.go
  test/test_images/runtime/handlers/file_access_attempt.go
  test/test_images/wsserver/echo.go
  test/util.go
Labels: lgtm, approved, size/L

#745 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#746 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
