Repository knative/networking, pull requests merged in 2022-05, with the labels that each got.

#665 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#666 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#667 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#669 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#668 Add label selector for secrets
  pkg/apis/networking/register.go
  test/conformance/ingress/util.go
Labels: lgtm, approved, size/XS, kind/enhancement

#672 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#674 move label to apis/networking
  pkg/apis/networking/register.go
  pkg/deprecated_labels.go
  pkg/labels/labels.go
Labels: lgtm, approved, size/M

#676 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S
