Repository knative/networking, pull requests merged in 2022-08, with the labels that each got.

#698 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#699 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#700 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#701 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#702 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#703 [release-1.7] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#704 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#705 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#706 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#707 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#708 httpproxy test image can setup TLS client with CA certs
  test/conformance/ingress/README.md
  test/conformance/ingress/util.go
  test/test_images/httpproxy/httpproxy.go
Labels: lgtm, approved, size/L, kind/enhancement
