Repository knative/networking, pull requests merged in 2022-04, with the labels that each got.

#645 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#646 drop knative.dev/release label
  config/certificate.yaml
  config/config-network.yaml
  config/domain-claim.yaml
  config/domain.yaml
  config/ingress.yaml
  config/realm.yaml
  config/serverlessservice.yaml
Labels: lgtm, approved, size/S

#647 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/L

#649 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#650 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#651 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#652 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#653 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#656 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#655 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#658 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#659 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: lgtm, approved, size/XS

#661 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#663 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#662 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#664 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S
