Repository knative/networking, pull requests merged in 2022-03, with the labels that each got.

#609 Support TLS server for each test image
  test/conformance/ingress/README.md
  test/conformance/ingress/util.go
  test/test_images/grpc-ping/main.go
  test/test_images/httpproxy/httpproxy.go
  test/test_images/retry/main.go
  test/test_images/runtime/main.go
  test/test_images/timeout/timeout.go
  test/test_images/wsserver/echo.go
  test/util.go
Labels: lgtm, approved, size/L

#627 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#629 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#630 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#631 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#633 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#632 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#634 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#635 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#636 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#637 Add validation for activator-ca and activator-san
  config/config-network.yaml
  pkg/network.go
  pkg/network_test.go
Labels: lgtm, approved, size/M

#639 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/M

#640 Add HTTPS port variables
  pkg/apis/networking/ports.go
Labels: lgtm, approved, size/XS

#641 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#642 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#643 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#644 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL
