Repository knative/networking, pull requests merged in 2022-10, with the labels that each got.

#715 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#717 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#718 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS, skip-review

#721 fix http01 conformance tests
  test/conformance/certificate/http01/certificate.go
Labels: lgtm, approved, size/XS

#723 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#724 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#725 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#726 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
