Repository knative/networking, pull requests merged in 2023-04, with the labels that each got.

#785 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#786 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#790 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#788 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#795 :broom: Bump Go version in github action to 1.19
  .github/workflows/knative-downstream.yaml
Labels: lgtm, approved, size/XS

#793 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: approved, size/S, skip-review

#796 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#797 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#798 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: lgtm, approved, size/S
