Repository knative/networking, pull requests merged in 2023-05, with the labels that each got.

#801 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#778 Add internal trust flag to config
  config/config-network.yaml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, size/L

#803 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#804 Add the new certificate names for dataplane and controlplane
  pkg/config/config.go
Labels: lgtm, approved, size/S

#806 Backward compatibility for InternalEncryption
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, size/XS

#808 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#809 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#812 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
