Repository knative/networking, pull requests merged in 2023-12, with the labels that each got.

#898 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#899 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/execabs/execabs.go
  vendor/golang.org/x/sys/execabs/execabs_go118.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#900 Add `TrustBundleLabelKey` to register
  pkg/apis/networking/register.go
Labels: lgtm, approved, size/XS
