Repository knative/networking, pull requests merged in 2023-02, with the labels that each got.

#758 update OWNERS file
  OWNERS
Labels: lgtm, approved, size/XS

#759 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#760 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#761 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#762 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#763 [release-1.7] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/configmap/load.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#765 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#764 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#766 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#767 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#774 [release-1.9] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS
