Repository knative/networking, pull requests merged in 2023-01, with the labels that each got.

#748 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#749 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#750 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#747 add new field 'Domain' to kcert spec
  config/certificate.yaml
  pkg/apis/networking/v1alpha1/certificate_types.go
  pkg/apis/networking/v1alpha1/certificate_validation.go
  pkg/apis/networking/v1alpha1/certificate_validation_test.go
Labels: lgtm, approved, size/M, kind/api-change

#751 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#752 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#753 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#754 adjust domain validation in kcert
  pkg/apis/networking/v1alpha1/certificate_validation.go
  pkg/apis/networking/v1alpha1/certificate_validation_test.go
Labels: lgtm, approved, size/S, kind/bug

#756 Assert all the expected DNSNames are part of the HTTP01 challenge
  test/conformance/certificate/http01/certificate.go
Labels: lgtm, approved, size/S
