Repository knative/networking, pull requests merged in 2023-10, with the labels that each got.

#858 Align the encryption flags
  README.md
  config/config-network.yaml
  pkg/apis/networking/metadata_validation.go
  pkg/apis/networking/metadata_validation_test.go
  pkg/apis/networking/register.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, size/L, kind/cleanup

#861 Cleanup SAN constants and Secrets Keys for system-internal-tls certificates
  pkg/certificates/constants.go
  pkg/certificates/reconciler/certificates.go
  pkg/certificates/reconciler/certificates_test.go
  pkg/certificates/reconciler/controller.go
  pkg/certificates/reconciler/controller_impl.go
  pkg/certificates/reconciler/reconciler.go
  pkg/config/config.go
Labels: lgtm, approved, size/L, kind/cleanup

#872 Rename cluster.local to avoid issues with config validation webhook
  config/config-network.yaml
Labels: lgtm, approved, size/XS

#874 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#877 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#880 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#881 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#882 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#883 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#884 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#885 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS
