Repository knative/networking, pull requests merged in 2024-12, with the labels that each got.

#1001 Make maximum delay of prober in its backoff configurable
  pkg/status/status.go
Labels: lgtm, approved, size/S, ok-to-test, kind/enhancement

#1026 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1027 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1028 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S
