Repository knative/networking, pull requests merged in 2024-04, with the labels that each got.

#958 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#959 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#961 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#962 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#964 some conformance tests assume we're getting back a runtime request
  test/conformance/ingress/headers.go
Labels: lgtm, approved, size/S

#957 Replace all usages of deprecated wait.PollImmediate with wait.PollUntilContextTimeout
  pkg/prober/prober.go
  pkg/prober/prober_test.go
  test/conformance/certificate/utils.go
  test/conformance/ingress/util.go
  test/ingress.go
Labels: lgtm, approved, size/S, ok-to-test

#965 fix TestRetry nil pointer panic
  test/conformance/ingress/retry.go
Labels: lgtm, approved, size/XS

#967 identify each request in update test using a query timestamp
  test/conformance/ingress/update.go
Labels: lgtm, approved, size/S

#968 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#970 Update test dialer to use ip when available
  test/conformance/ingress/util.go
Labels: lgtm, approved, size/L, kind/bug

#972 Remove requestDelay flag for tests
  test/conformance/ingress/timeout.go
  test/conformance/ingress/util.go
  test/e2e_flags.go
Labels: lgtm, approved, size/S, kind/cleanup

#975 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
