Repository knative/networking, pull requests merged in 2024-02, with the labels that each got.

#920 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#921 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#922 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#923 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#924 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#927 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#926 feat: add isFailed for certificate
  pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  pkg/apis/networking/v1alpha1/certificate_lifecycle_test.go
Labels: lgtm, approved, size/S, needs-ok-to-test, kind/enhancement

#928 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#930 drop net-http01 from downstream testing
  .github/workflows/knative-downstream.yaml
Labels: lgtm, approved, size/XS

#931 bump golang to v1.22
  .github/workflows/knative-downstream.yaml
  config/certificate.yaml
  config/domain-claim.yaml
  config/domain.yaml
  config/ingress.yaml
  config/realm.yaml
  config/serverlessservice.yaml
  hack/update-schemas.sh
Labels: lgtm, approved, size/XL

#932 Update grpc/h2c conformance test
  test/conformance/ingress/util.go
Labels: lgtm, approved, size/XS

#935 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#934 Exclude test folder from code coverage calculation
  .codecov.yaml
Labels: lgtm, approved, size/XS

#936 add the h2c app protocol value for the HTTP2 test
  test/conformance/ingress/basic.go
  test/conformance/ingress/util.go
Labels: lgtm, approved, size/S

#937 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/LICENSE
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#933 drop unused types
  config/domain.yaml
  config/realm.yaml
  pkg/apis/networking/v1alpha1/domain_defaults.go
  pkg/apis/networking/v1alpha1/domain_defaults_test.go
  pkg/apis/networking/v1alpha1/domain_lifecycle.go
  pkg/apis/networking/v1alpha1/domain_lifecycle_test.go
  pkg/apis/networking/v1alpha1/domain_types.go
  pkg/apis/networking/v1alpha1/domain_types_test.go
  pkg/apis/networking/v1alpha1/domain_validation.go
  pkg/apis/networking/v1alpha1/domain_validation_test.go
  pkg/apis/networking/v1alpha1/realm_defaults.go
  pkg/apis/networking/v1alpha1/realm_defaults_test.go
  pkg/apis/networking/v1alpha1/realm_lifecycle.go
  pkg/apis/networking/v1alpha1/realm_lifecycle_test.go
  pkg/apis/networking/v1alpha1/realm_types.go
  pkg/apis/networking/v1alpha1/realm_types_test.go
  pkg/apis/networking/v1alpha1/realm_validation.go
  pkg/apis/networking/v1alpha1/realm_validation_test.go
  pkg/apis/networking/v1alpha1/register.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/networking/v1alpha1/domain.go
  pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_domain.go
  pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_networking_client.go
  pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_realm.go
  pkg/client/clientset/versioned/typed/networking/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/networking/v1alpha1/networking_client.go
  pkg/client/clientset/versioned/typed/networking/v1alpha1/realm.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/networking/v1alpha1/domain.go
  pkg/client/informers/externalversions/networking/v1alpha1/interface.go
  pkg/client/informers/externalversions/networking/v1alpha1/realm.go
  pkg/client/injection/informers/networking/v1alpha1/domain/domain.go
  pkg/client/injection/informers/networking/v1alpha1/domain/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/domain/filtered/domain.go
  pkg/client/injection/informers/networking/v1alpha1/domain/filtered/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/realm/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/realm/filtered/fake/fake.go
  pkg/client/injection/informers/networking/v1alpha1/realm/filtered/realm.go
  pkg/client/injection/informers/networking/v1alpha1/realm/realm.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/domain/state.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/controller.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/reconciler.go
  pkg/client/injection/reconciler/networking/v1alpha1/realm/state.go
  pkg/client/listers/networking/v1alpha1/domain.go
  pkg/client/listers/networking/v1alpha1/expansion_generated.go
  pkg/client/listers/networking/v1alpha1/realm.go
Labels: size/XXL, lgtm, approved
