Repository knative/networking, pull requests merged in 2024-03, with the labels that each got.

#939 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#941 chore: drop OWNER files from ./test & ./hack
  hack/OWNERS
  test/OWNERS
Labels: lgtm, approved, size/S

#940 cleanup: drop unused e2e files
  test/e2e-common.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: lgtm, approved, size/M

#942 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#943 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#945 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#946 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#947 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#948 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#949 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#950 Drop special logic for kubelet probe header for istio
  pkg/http/header/header.go
Labels: lgtm, approved, size/S

#952 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#951 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#953 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#955 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/modules.txt
Labels: lgtm, approved, size/S
