Repository knative/networking, pull requests merged in 2025-02, with the labels that each got.

#1045 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/spf13/pflag/.editorconfig
  vendor/github.com/spf13/pflag/.golangci.yaml
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1048 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1049 fix linter config
  .golangci.yaml
Labels: lgtm, approved, size/XS
